version: '2.0'
services:
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  web:
    volumes:
      - .:/code
      - ./log:/app/log
    image: chatroom_web
    build:
      context: .
      dockerfile: deploy/Dockerfile
    ports:
      - "5000:5000"
    links:
      - "db:db"
    depends_on:
      - "db"
